### ISSUE TITLE
File included not found

### ISSUE THREAD

**Issue by abdilahrf** [voided/dota-voidhack#1]
when i build the program , many file included is not found , can you fix that ?

**Comment by zakadx** [comment]
you can tell this guy https://github.com/VoiDeD/dota-voidhack

**Comment by voided** [comment]
> when i build the program , many file included is not found , can you fix that ?

Nope, you're on your own.

**Comment by zakadx** [comment]
VoiDed where I should put this hack void dota file?

**Comment by abdilahrf** [comment]
@VoiDeD  : not get the idea
